### ISSUE TITLE
system-transparency task integration Roadmap

### ISSUE THREAD

**Issue by sylv-io** [go-task/task#501]
Hi everyone. Thanks for the development of this great build tool!
It Indeed looks like it suits well as an alternative build tool for GNU make.

This issue is intended as a roadmap for the integration of task in [system-transparency](https://github.com/system-transparency/system-transparency). 

## Background

At the moment the [system-transparency](https://github.com/system-transparency/system-transparency)  uses GNU make for different build task. Many of the required some make shenanigans to work and the whole environment looks unnecessarily complicated (i am partly to blame :sweat_smile:). To simplify it's build environment we where looking for an alternative for a long time. Fortunately, the Google search `GNU make alternative in go`  has made us aware of this project and its amazing  [documentation](https://taskfile.dev/). Which addition of some simple PoC tests we concluded it fits well as an alternative except for some minor missing features, on which we would love to contribute.

## Contribution

We would like to support the development of this tool and bring the development forward.
Our main goal is to be able to use the upstream task tool and not rely on our own [fork](https://github.com/system-transparency/task). Luckily, most of the missing features where already requested by other users or exist as pending PR. However, more are likely to be added in the course the integration. In addition, it would be also great to somehow improve the discoverability of this project, so that it gets the attention that it deserves.

## Roadmap

*This list is still WIP*
 
Currently, there are 3 types of features with different priority for the integration:
Required features (with and without a workaround) and optional features (nice to have).
 
### required features (no workaround)

- [x] Support source and status #411 #477
- [x]  Add `interactive` bool to force interleaved output #217

### required features (with workaround)

- [ ] Rebuild if specific environment variable changes #394 
- [x] Run dependency once (configurable) #53
- [ ] Override environment variables  #449  #482
- [x] task: Check context error #598

**Comment by sylv-io** [comment]
And sorry for highjacking the feature request template :sweat_smile:. I thought a roadmap like issue would be the best method summarize our background and the interest to contribute. :+1:

**Comment by andreynering** [comment]
Hi @sylv-io, thanks for opening this issue!

It's nice to see Task getting more adoption 🙂.

Regarding #411 and #477, that's just a matter of time, since it's an easy fix. The open PR likely need a few adjustments but I plan to do that in the near future.

Regarding #394, I just posted a workaround here (but it will only work for checksum mode, though): https://github.com/go-task/task/issues/394#issuecomment-860255357.

#53 is a little but trickier, but it'll likely be a reality some day.

**Comment by sylv-io** [comment]
Hi @andreynering, thanks for the answer!

> Regarding #411 and #477, that's just a matter of time, since it's an easy fix. The open PR likely need a few adjustments but I plan to do that in the near future.

Sounds good to me. I''ll use our fork until then.

> Regarding #394, I just posted a workaround here (but it will only work for checksum mode, though): [#394 (comment)](https://github.com/go-task/task/issues/394#issuecomment-860255357).

Indeed it looks like a great workaround :+1: I will try it out.

I will start the integration now. I hope everything goes well :grin:

**Comment by sylv-io** [comment]
I added `Override environment variables` since we need to override them in some cases (e.g go specific variables like GOPATH and GO111MODULE).
A workaround is to run export to override the variable for each command.

**Comment by max-sixty** [comment]
> Regarding #411 and #477, that's just a matter of time, since it's an easy fix. The open PR likely need a few adjustments but I plan to do that in the near future.
> 
> #53 is a little but trickier, but it'll likely be a reality some day.

@andreynering speaking as a big fan of go-task and a maintainer of other OSS libraries — and forgive me if I'm speaking out of turn:

Could you ask for more contributions rather than doing so much yourself? I notice that often people often refer to their fork, and may well be happy to provide the code to the central project, if you were to set out your requirements for merging them. That might allow you to leverage yourself more, and let your project move faster?

**Comment by andreynering** [comment]
Hi @max-sixty,

You have a point that having external contributions is a good thing. I think that's actually happening, but I've been failing into reviewing these PRs. #53 you mentioned has a PR opened since August 2020, for example: #359.

I think part of the problem is there are many issues been opened about questions / bug reports / features requests, and my time is split between answering those and actually writing code and reviewing PRs.

So, I'd say some help with answering simple questions would already be welcome. If you have more suggestions on what we could do, let me know.

**Comment by andreynering** [comment]
I'll release #411 / #477 today, and try to release #53 / #359 in the coming weeks as well.

**Comment by max-sixty** [comment]
Thanks for your thoughtful reply @andreynering .

It's your project, and you'll have to decide how much to accept others' contributions as you balance growth vs quality. Contributions from others will never be exactly what you want!

One thing I'll add is that providing feedback to contributions inspires more contributions (and vice versa). And so the payoff may not be immediate — but over time you'll find some people who really like the project and learn their way around, and become prolific contributors, and then can start offering feedback on further contributions themselves, etc.

Let me know anything I can do to help! Again thank you for providing this library, I'm a big fan.

**Comment by andreynering** [comment]
#53 / #359 was just released!

**Comment by sylv-io** [comment]
> #53 / #359 was just released!

great! thanks for the hint

**Comment by sylv-io** [comment]
As mentioned [here](https://github.com/go-task/task/issues/394#issuecomment-889773804) I will try to contribute to this feature myself :+1: . The system-transparency migration to taskfile is already well [advanced](https://github.com/system-transparency/system-transparency/tree/taskfile).

**Comment by sylv-io** [comment]
Task integration was merged into system-transparency: https://github.com/system-transparency/system-transparency/pull/117 :+1:

**Comment by sylv-io** [comment]
Oh, I forgot to close this issue.
The integration is complete and everything is working like a charm.
Thanks for this awesome tool :heart:
